camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  license-file: classpath:license.key.txt
  history-level: full
  deployment-resource-pattern: classpath:/processesc7/**/*.bpmn

server.port: 8080

#zeebe.client.broker.gatewayAddress=127.0.0.1:26500
#zeebe.client.security.plaintext=true